feat：First version commit
bitfocus/companion-module-kommander-t3 pull request #1
Opened 2024-05-10 03:22 UTC by howcoder

The code is for some functions of Kommander, if there is any non-standard place, please correct, thank you  very much

2024-05-14 10:13 UTC, dnmeid requested changes
Generally there is still a lot of just copied and unadjusted code, you will have to correct that.
Please consider better naming and spelling of your action names and option labels.
Please add presets.
Please add feedbacks.

2024-05-14 10:13 UTC, dnmeid commented on README.md
> +# companion-module-generic-websocket
Correct name

2024-05-14 10:13 UTC, dnmeid commented on README.md
> +See HELP.md and LICENSE
Suggest keeping the links

2024-05-14 10:13 UTC, dnmeid commented on companion/manifest.json
> +	"id": "kommander-module",
THis need to be the repo name without companion-module-, i.e. `kommander-t3`

2024-05-14 10:13 UTC, dnmeid commented on companion/manifest.json
> +	"repository": "git+https://gitee.com/xuweijun_admin/kommander-bitfocus-companion",
Change to repo under bitfocus

2024-05-14 10:13 UTC, dnmeid commented on companion/manifest.json
> +	"bugs": "https://gitee.com/xuweijun_admin/kommander-bitfocus-companion/issues",
Change to repo under bitfocus

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +class WebsocketInstance extends InstanceBase {
Suggest individual class name

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +			this.updateStatus(InstanceStatus.BadConfig, `WS URL is not defined or invalid`)
Misleading error message

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +			{
You just copy generic module, you have to adjust it.

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +			websocket_variable: {
THis feedback is just copied from generic module, please write fitting feedbacks for your product.

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +			{ id: 'PreviewPlan', label: 'PreviewPlan' },
Do you mean "previous" instead of preview? Please check everywhere.

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +					const value = await context.parseVariablesInString(action.options.pageTurn)
value seems to be unused

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +            case 'Brightness+':
why you leave this case empty and do a less explicit check in the next case? Better set correct KommanderMsg and params in every possible case.

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +			this.ws.send(JSON.stringify({
Are the hardcoded parameters correct?

2024-05-14 10:13 UTC, dnmeid commented on upgrade.js
> +	function v2_1(context, props) {
You just copy from generic module. Your v1.0.0 should not need an upgrade script.

2024-05-14 10:13 UTC, dnmeid commented on package.json
> +	"name": "generic-websocket",
Please correct

2024-05-14 10:13 UTC, dnmeid commented on package.json
> +	"version": "2.1.0",
Please correct

2024-05-14 10:13 UTC, dnmeid commented on package.json
> +		"url": "git+https://github.com/bitfocus/companion-module-generic-websocket.git"
Please correct

2024-05-14 10:13 UTC, dnmeid commented on companion/manifest.json
> +	"version": "1.0.0",
Should stay at `0.0.0` in manifest.json

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +				name: 'CallPlan',
Please consider more human friendly names like `Call Plan` unless `CallPlan` is also used in the GUI of Kommander and will be better recognised by your users.

2024-05-14 10:13 UTC, dnmeid commented on main.js
> +							{ id: -1, label: 'volume+' },
Please check for consistent uppercase/lowercase writing, e.g. `Volume +` would be better here.

2024-05-16 06:45 UTC, howcoder commented on main.js
> +			{
I deleted the unnecessary content and kept the necessary ones

2024-05-16 06:46 UTC, howcoder commented on main.js
> +			websocket_variable: {
I haven't used feedback yet, I commented it out in the init method

2024-05-16 06:47 UTC, howcoder commented on main.js
> +			{ id: 'PreviewPlan', label: 'PreviewPlan' },
Yes, thank you for your advice

2024-05-16 06:48 UTC, howcoder commented on main.js
> +			this.ws.send(JSON.stringify({
Yes, I'm sure.

2024-05-16 06:49 UTC, howcoder commented on main.js
> +				name: 'CallPlan',
This is exactly what I want to use CallPlan

2024-05-18 15:04 UTC, dnmeid requested changes

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.data)
there is no option with the id `data`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.data)
again no option with id `data`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.data)
again no option with id `data`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.data)
again no option with id `data`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
the option `pageTurn` is of type dropdown, so parsing variables in the option value does not make sense. Additionally you do not use `value`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
There is no option with id `pageTurn`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
there is no option with id `pageTurn`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
there is no option with id `pageTurn`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
there is no option with id `pageTurn`

2024-05-18 15:04 UTC, dnmeid commented on main.js
> +            const value = await context.parseVariablesInString(action.options.pageTurn)
there is no option with id `pageTurn`

2024-05-18 15:04 UTC, dnmeid commented on package.json
> +	"version": "0.0.0",
Here you need the real version of the module. At least 1.0.0 for first release

2024-06-26 18:59 UTC, dnmeid requested changes

2024-06-26 18:59 UTC, dnmeid commented on main.js
> +				regex: '/' + this.wsRegex + '/',
please add a default value, otherwise it will be undefined.
e.g. 'ws://' or ''

2024-06-26 18:59 UTC, dnmeid commented on main.js
> +			{
Not really

2024-06-26 18:59 UTC, dnmeid commented on main.js
> +			websocket_variable: {
So please write some feedbacks then.

2025-02-28 18:49 UTC, merged

2025-02-28 19:04 UTC, dnmeid commented
@howcoder Thank you for your patience. I just lost track of this pr waiting for approval.
I now did merge it and also made a release and published it. The module is now available in the beta version of Companion and will be part of the next release.

2025-03-01 01:41 UTC, howcoder commented
@dnmeid Thank you so much for your response and for merging the PR!  I really appreciate your effort in making the release and publishing it.  It's great to know that the module is now available in the beta version and will be part of the next official release.  Thanks again for your support and for keeping me updated!  😊